### ISSUE TITLE
Error when downloading pretrained resnet200

### ISSUE THREAD

**Issue by lwoiceshyn** [rwightman/pytorch-planet-amazon#1]
Downloading: "https://www.dropbox.com/s/tchq8fbdd4wabjx/fbresnet_200-37304a01b.pth?dl=1" to 

/home/leow/.torch/models/fbresnet_200-37304a01b.pth
Traceback (most recent call last):
  File "/home/leow/anaconda3/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/leow/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/leow/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/leow/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/leow/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/leow/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/leow/anaconda3/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/home/leow/anaconda3/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/home/leow/anaconda3/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/home/leow/anaconda3/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/home/leow/anaconda3/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

It seems that the download link doesn't work.

**Comment by rwightman** [comment]
That's a link to my own dropbox. It worked last time I tried, and still seems to work for me. Try manually if not. There are limits on how much can be downloaded so maybe they were hit. If anything I'll be stripping those links, not replacing them as I do not have a better or alternate hosting solution...

**Comment by rwightman** [comment]
You can also re-create the pth if you use the https://github.com/clcarwin/convert_torch_to_pytorch  converter on the ResNet-200 t7 from https://github.com/facebook/fb.resnet.torch/tree/master/pretrained

**Comment by lwoiceshyn** [comment]
When I run the torch converter on that file, I get an error because the t7
file has Cuda tensors in it:

AttributeError: type object 'torch.cuda.FloatStorage' has no attribute
'from_buffer'

Did you run into this issue?

Regards,
Leo

**Comment by rwightman** [comment]
Right, that's a problem.

If you've got torch7 installed, from the th console you can do the following to convert it from a cuda model to a cpu float which will work with the conversion script...

th> import 'cudnn'
th> model = torch.load('./resnet-200.t7')
th> model = model:float()
th> torch.save('./resnet-200-cpu.t7', model)
